### ISSUE TITLE
Build a UI prototype with Streamlit

### ISSUE THREAD

**Issue by viktorbengtsson** [viktorbengtsson/pypsa-vgr#26]
Should contain:
- A map
- A pie chart showing the ratio of energy types
- Some sort of line or area chart showing consumption, production
- A table describing the power system, number of wind turbines, MW, battery capacity in days etc. and costs
- A slider to set the power target
- Some inputs for some reasonable things (no hydrogen, curtail onwind)

**Comment by fredrikcelin** [comment]
* 16:9
* Larger map
* Energy charts: Area chart instead (mjuka till) + Demand (linje)
* QR code
* The table from Viktor dashboard (under the network map). Liggande stapel.
* Choose more appropriate Turbines (offshore 20, onshore 5, Ingen cutout?). Ta Vestas. (Kanske olika för target-år?)
* ....and solar panels
* Skippa pajen
* Stående stapel: Det som vi har idag pajen på (nominell effekt)
* Elprodiktionsmål (Twh) 1 to 25/30
* Ny filter: Vindkraftscenario: "Statisk", "Försiktig", "Aggresiv" + Havsvind av/på + Vätgas till industri: "Liten", "Medel", "Stor"
*
